#!/bin/bash

echo "🚀 Preparando deploy do Swing Trade Manager"
echo ""
echo "📋 Checklist:"
echo ""
echo "1. ✅ Arquivos de configuração criados"
echo "2. ✅ .gitignore atualizado"
echo "3. ✅ Backend pronto para deploy"
echo ""
echo "🎯 Próximos passos:"
echo ""
echo "1. Criar conta no Render.com (https://render.com)"
echo "2. Conectar com GitHub"
echo "3. Criar novo Web Service do repositório 09Uno/swing-trade"
echo "4. Configurar variáveis de ambiente:"
echo "   - ADMIN_USERNAME=seu_usuario"
echo "   - ADMIN_PASSWORD=sua_senha"
echo "   - JWT_SECRET=seu_segredo_longo"
echo "   - FRONTEND_URL=https://09uno.github.io"
echo "   - NODE_ENV=production"
echo ""
echo "5. Após deploy, copiar a URL do backend"
echo "6. Atualizar login.html e index.html com a URL"
echo ""
echo "📖 Leia DEPLOY-BACKEND.md para instruções completas!"
echo ""
